// <auto-generated />
using System;
using DSecureApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSecureApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024043035_AddEnhancedUserFields")]
    partial class AddEnhancedUserFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BitRaserApiProject.Models.Commands", b =>
                {
                    b.Property<int>("Command_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("command_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("command_status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("command_text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("issued_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Command_id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.GeneratedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReportTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("GeneratedReports");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.Group", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("license_allocation")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("permissions_json")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("group_id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3062),
                            Description = "Complete system access",
                            PermissionName = "FullAccess"
                        },
                        new
                        {
                            PermissionId = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3066),
                            Description = "Manage users and subusers",
                            PermissionName = "UserManagement"
                        },
                        new
                        {
                            PermissionId = 3,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3069),
                            Description = "Access and manage audit reports",
                            PermissionName = "ReportAccess"
                        },
                        new
                        {
                            PermissionId = 4,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3072),
                            Description = "Manage machines",
                            PermissionName = "MachineManagement"
                        },
                        new
                        {
                            PermissionId = 5,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3074),
                            Description = "Read-only access",
                            PermissionName = "ViewOnly"
                        },
                        new
                        {
                            PermissionId = 6,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3077),
                            Description = "Manage licenses",
                            PermissionName = "LicenseManagement"
                        },
                        new
                        {
                            PermissionId = 7,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3080),
                            Description = "Access system logs",
                            PermissionName = "SystemLogs"
                        },
                        new
                        {
                            PermissionId = 8,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3083),
                            Description = "View all machines in the system",
                            PermissionName = "READ_ALL_MACHINES"
                        },
                        new
                        {
                            PermissionId = 9,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3085),
                            Description = "View individual machine details",
                            PermissionName = "READ_MACHINE"
                        },
                        new
                        {
                            PermissionId = 10,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3088),
                            Description = "Register new machines",
                            PermissionName = "CREATE_MACHINE"
                        },
                        new
                        {
                            PermissionId = 11,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3090),
                            Description = "Update machine information",
                            PermissionName = "UPDATE_MACHINE"
                        },
                        new
                        {
                            PermissionId = 12,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3093),
                            Description = "Update any machine in system",
                            PermissionName = "UPDATE_ALL_MACHINES"
                        },
                        new
                        {
                            PermissionId = 13,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3096),
                            Description = "Remove machines from system",
                            PermissionName = "DELETE_MACHINE"
                        },
                        new
                        {
                            PermissionId = 14,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3098),
                            Description = "Remove any machine in system",
                            PermissionName = "DELETE_ALL_MACHINES"
                        },
                        new
                        {
                            PermissionId = 15,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3101),
                            Description = "Activate, deactivate, and renew licenses",
                            PermissionName = "MANAGE_MACHINE_LICENSES"
                        },
                        new
                        {
                            PermissionId = 16,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3103),
                            Description = "Manage licenses for any machine",
                            PermissionName = "MANAGE_ALL_MACHINE_LICENSES"
                        },
                        new
                        {
                            PermissionId = 17,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3106),
                            Description = "View machine analytics and statistics",
                            PermissionName = "READ_MACHINE_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 18,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3109),
                            Description = "View machines for managed users",
                            PermissionName = "READ_MANAGED_USER_MACHINES"
                        },
                        new
                        {
                            PermissionId = 19,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3111),
                            Description = "View all users in the system",
                            PermissionName = "READ_ALL_USERS"
                        },
                        new
                        {
                            PermissionId = 20,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3114),
                            Description = "View individual user details",
                            PermissionName = "READ_USER"
                        },
                        new
                        {
                            PermissionId = 21,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3116),
                            Description = "View users in management hierarchy",
                            PermissionName = "READ_MANAGED_USERS"
                        },
                        new
                        {
                            PermissionId = 22,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3119),
                            Description = "Create new user accounts",
                            PermissionName = "CREATE_USER"
                        },
                        new
                        {
                            PermissionId = 23,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3121),
                            Description = "Update user information",
                            PermissionName = "UPDATE_USER"
                        },
                        new
                        {
                            PermissionId = 24,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3124),
                            Description = "Remove user accounts",
                            PermissionName = "DELETE_USER"
                        },
                        new
                        {
                            PermissionId = 25,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3126),
                            Description = "Assign and remove user roles",
                            PermissionName = "ASSIGN_ROLES"
                        },
                        new
                        {
                            PermissionId = 26,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3129),
                            Description = "Change user passwords",
                            PermissionName = "CHANGE_USER_PASSWORDS"
                        },
                        new
                        {
                            PermissionId = 27,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3132),
                            Description = "View user analytics and statistics",
                            PermissionName = "READ_USER_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 28,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3256),
                            Description = "Manage user reporting relationships",
                            PermissionName = "MANAGE_USER_HIERARCHY"
                        },
                        new
                        {
                            PermissionId = 29,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3259),
                            Description = "View all subusers in the system",
                            PermissionName = "READ_ALL_SUBUSERS"
                        },
                        new
                        {
                            PermissionId = 30,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3261),
                            Description = "View individual subuser details",
                            PermissionName = "READ_SUBUSER"
                        },
                        new
                        {
                            PermissionId = 31,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3264),
                            Description = "View subusers for managed users",
                            PermissionName = "READ_USER_SUBUSERS"
                        },
                        new
                        {
                            PermissionId = 32,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3267),
                            Description = "Create new subuser accounts",
                            PermissionName = "CREATE_SUBUSER"
                        },
                        new
                        {
                            PermissionId = 33,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3269),
                            Description = "Create subusers for other users",
                            PermissionName = "CREATE_SUBUSERS_FOR_OTHERS"
                        },
                        new
                        {
                            PermissionId = 34,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3272),
                            Description = "Update subuser information",
                            PermissionName = "UPDATE_SUBUSER"
                        },
                        new
                        {
                            PermissionId = 35,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3275),
                            Description = "Update any subuser in system",
                            PermissionName = "UPDATE_ALL_SUBUSERS"
                        },
                        new
                        {
                            PermissionId = 36,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3277),
                            Description = "Remove subuser accounts",
                            PermissionName = "DELETE_SUBUSER"
                        },
                        new
                        {
                            PermissionId = 37,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3280),
                            Description = "Remove any subuser in system",
                            PermissionName = "DELETE_ALL_SUBUSERS"
                        },
                        new
                        {
                            PermissionId = 38,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3282),
                            Description = "Change subuser passwords",
                            PermissionName = "CHANGE_SUBUSER_PASSWORD"
                        },
                        new
                        {
                            PermissionId = 39,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3285),
                            Description = "Change any subuser password",
                            PermissionName = "CHANGE_ALL_SUBUSER_PASSWORDS"
                        },
                        new
                        {
                            PermissionId = 40,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3288),
                            Description = "Assign roles to subusers",
                            PermissionName = "ASSIGN_SUBUSER_ROLES"
                        },
                        new
                        {
                            PermissionId = 41,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3290),
                            Description = "Assign roles to any subuser",
                            PermissionName = "ASSIGN_ALL_SUBUSER_ROLES"
                        },
                        new
                        {
                            PermissionId = 42,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3293),
                            Description = "Remove roles from subusers",
                            PermissionName = "REMOVE_SUBUSER_ROLES"
                        },
                        new
                        {
                            PermissionId = 43,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3295),
                            Description = "Remove roles from any subuser",
                            PermissionName = "REMOVE_ALL_SUBUSER_ROLES"
                        },
                        new
                        {
                            PermissionId = 44,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3298),
                            Description = "Reassign subusers to different parents",
                            PermissionName = "REASSIGN_SUBUSERS"
                        },
                        new
                        {
                            PermissionId = 45,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3301),
                            Description = "View subuser analytics and statistics",
                            PermissionName = "READ_SUBUSER_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 46,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3303),
                            Description = "View system-wide subuser analytics",
                            PermissionName = "READ_ALL_SUBUSER_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 47,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3306),
                            Description = "View all audit reports",
                            PermissionName = "READ_ALL_REPORTS"
                        },
                        new
                        {
                            PermissionId = 48,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3308),
                            Description = "View individual report details",
                            PermissionName = "READ_REPORT"
                        },
                        new
                        {
                            PermissionId = 49,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3311),
                            Description = "View reports for managed users",
                            PermissionName = "READ_USER_REPORTS"
                        },
                        new
                        {
                            PermissionId = 50,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3314),
                            Description = "Create reports on behalf of other users",
                            PermissionName = "CREATE_REPORTS_FOR_OTHERS"
                        },
                        new
                        {
                            PermissionId = 51,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3316),
                            Description = "Update any report in system",
                            PermissionName = "UPDATE_ALL_REPORTS"
                        },
                        new
                        {
                            PermissionId = 52,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3319),
                            Description = "Update own reports",
                            PermissionName = "UPDATE_REPORT"
                        },
                        new
                        {
                            PermissionId = 53,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3322),
                            Description = "Delete any report in system",
                            PermissionName = "DELETE_ALL_REPORTS"
                        },
                        new
                        {
                            PermissionId = 54,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3324),
                            Description = "Delete own reports",
                            PermissionName = "DELETE_REPORT"
                        },
                        new
                        {
                            PermissionId = 55,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3327),
                            Description = "Export reports to PDF/CSV",
                            PermissionName = "EXPORT_REPORTS"
                        },
                        new
                        {
                            PermissionId = 56,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3329),
                            Description = "Export any reports in system",
                            PermissionName = "EXPORT_ALL_REPORTS"
                        },
                        new
                        {
                            PermissionId = 57,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3332),
                            Description = "View report analytics",
                            PermissionName = "READ_REPORT_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 58,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3335),
                            Description = "View system-wide report analytics",
                            PermissionName = "READ_ALL_REPORT_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 59,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3337),
                            Description = "View all system commands",
                            PermissionName = "READ_ALL_COMMANDS"
                        },
                        new
                        {
                            PermissionId = 60,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3340),
                            Description = "View individual command details",
                            PermissionName = "READ_COMMAND"
                        },
                        new
                        {
                            PermissionId = 61,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3342),
                            Description = "Create new commands",
                            PermissionName = "CREATE_COMMAND"
                        },
                        new
                        {
                            PermissionId = 62,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3345),
                            Description = "Update command information",
                            PermissionName = "UPDATE_COMMAND"
                        },
                        new
                        {
                            PermissionId = 63,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3347),
                            Description = "Update command execution status",
                            PermissionName = "UPDATE_COMMAND_STATUS"
                        },
                        new
                        {
                            PermissionId = 64,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3350),
                            Description = "Remove commands from system",
                            PermissionName = "DELETE_COMMAND"
                        },
                        new
                        {
                            PermissionId = 65,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3352),
                            Description = "Full command management access",
                            PermissionName = "MANAGE_COMMANDS"
                        },
                        new
                        {
                            PermissionId = 66,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3355),
                            Description = "View command analytics and statistics",
                            PermissionName = "READ_COMMAND_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 67,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3357),
                            Description = "Bulk update multiple commands",
                            PermissionName = "BULK_UPDATE_COMMANDS"
                        },
                        new
                        {
                            PermissionId = 68,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3360),
                            Description = "View all user sessions",
                            PermissionName = "READ_ALL_SESSIONS"
                        },
                        new
                        {
                            PermissionId = 69,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3363),
                            Description = "View individual session details",
                            PermissionName = "READ_SESSION"
                        },
                        new
                        {
                            PermissionId = 70,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3365),
                            Description = "View sessions for managed users",
                            PermissionName = "READ_USER_SESSIONS"
                        },
                        new
                        {
                            PermissionId = 71,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3368),
                            Description = "End own sessions",
                            PermissionName = "END_SESSION"
                        },
                        new
                        {
                            PermissionId = 72,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3370),
                            Description = "End any user session",
                            PermissionName = "END_ALL_SESSIONS"
                        },
                        new
                        {
                            PermissionId = 73,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3373),
                            Description = "End sessions for managed users",
                            PermissionName = "END_USER_SESSIONS"
                        },
                        new
                        {
                            PermissionId = 74,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3375),
                            Description = "Extend session duration",
                            PermissionName = "EXTEND_SESSION"
                        },
                        new
                        {
                            PermissionId = 75,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3378),
                            Description = "View session analytics",
                            PermissionName = "READ_SESSION_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 76,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3381),
                            Description = "View system-wide session analytics",
                            PermissionName = "READ_ALL_SESSION_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 77,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3383),
                            Description = "Clean up expired sessions",
                            PermissionName = "CLEANUP_SESSIONS"
                        },
                        new
                        {
                            PermissionId = 78,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3386),
                            Description = "View all system logs",
                            PermissionName = "READ_ALL_LOGS"
                        },
                        new
                        {
                            PermissionId = 79,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3388),
                            Description = "View individual log entries",
                            PermissionName = "READ_LOG"
                        },
                        new
                        {
                            PermissionId = 80,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3391),
                            Description = "View logs for managed users",
                            PermissionName = "READ_USER_LOGS"
                        },
                        new
                        {
                            PermissionId = 81,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3393),
                            Description = "Create new log entries",
                            PermissionName = "CREATE_LOG"
                        },
                        new
                        {
                            PermissionId = 82,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3396),
                            Description = "Remove log entries",
                            PermissionName = "DELETE_LOG"
                        },
                        new
                        {
                            PermissionId = 83,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3399),
                            Description = "Advanced log search capabilities",
                            PermissionName = "SEARCH_LOGS"
                        },
                        new
                        {
                            PermissionId = 84,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3401),
                            Description = "Export logs to CSV/other formats",
                            PermissionName = "EXPORT_LOGS"
                        },
                        new
                        {
                            PermissionId = 85,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3404),
                            Description = "Export any logs in system",
                            PermissionName = "EXPORT_ALL_LOGS"
                        },
                        new
                        {
                            PermissionId = 86,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3406),
                            Description = "View log analytics",
                            PermissionName = "READ_LOG_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 87,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3409),
                            Description = "View system-wide log analytics",
                            PermissionName = "READ_ALL_LOG_STATISTICS"
                        },
                        new
                        {
                            PermissionId = 88,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3411),
                            Description = "Clean up old log entries",
                            PermissionName = "CLEANUP_LOGS"
                        },
                        new
                        {
                            PermissionId = 89,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3414),
                            Description = "View own profile information",
                            PermissionName = "VIEW_PROFILE"
                        },
                        new
                        {
                            PermissionId = 90,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3417),
                            Description = "Update own profile information",
                            PermissionName = "UPDATE_PROFILE"
                        },
                        new
                        {
                            PermissionId = 91,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3419),
                            Description = "View other user profiles",
                            PermissionName = "VIEW_USER_PROFILE"
                        },
                        new
                        {
                            PermissionId = 92,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3501),
                            Description = "View sensitive profile information",
                            PermissionName = "VIEW_SENSITIVE_PROFILE_INFO"
                        },
                        new
                        {
                            PermissionId = 93,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3503),
                            Description = "View user hierarchy and reporting relationships",
                            PermissionName = "VIEW_HIERARCHY"
                        },
                        new
                        {
                            PermissionId = 94,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3506),
                            Description = "View complete organizational hierarchy",
                            PermissionName = "VIEW_ORGANIZATION_HIERARCHY"
                        },
                        new
                        {
                            PermissionId = 95,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3509),
                            Description = "Manage user hierarchy and reporting relationships",
                            PermissionName = "MANAGE_HIERARCHY"
                        },
                        new
                        {
                            PermissionId = 96,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3511),
                            Description = "Assign direct reports to managers",
                            PermissionName = "ASSIGN_DIRECT_REPORTS"
                        },
                        new
                        {
                            PermissionId = 97,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3514),
                            Description = "Search users across the system",
                            PermissionName = "SEARCH_USERS"
                        },
                        new
                        {
                            PermissionId = 98,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3516),
                            Description = "View profile analytics and statistics",
                            PermissionName = "VIEW_PROFILE_ANALYTICS"
                        },
                        new
                        {
                            PermissionId = 99,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3519),
                            Description = "Manage relationships between users",
                            PermissionName = "MANAGE_USER_RELATIONSHIPS"
                        },
                        new
                        {
                            PermissionId = 100,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3521),
                            Description = "View user activity and recent actions",
                            PermissionName = "VIEW_USER_ACTIVITY"
                        },
                        new
                        {
                            PermissionId = 101,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3524),
                            Description = "Export user profile and activity data",
                            PermissionName = "EXPORT_USER_DATA"
                        },
                        new
                        {
                            PermissionId = 102,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3527),
                            Description = "View profiles of subordinate users",
                            PermissionName = "VIEW_SUBORDINATE_PROFILES"
                        },
                        new
                        {
                            PermissionId = 103,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3529),
                            Description = "Manage team member profiles and assignments",
                            PermissionName = "MANAGE_TEAM_MEMBERS"
                        },
                        new
                        {
                            PermissionId = 104,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3532),
                            Description = "System administration access",
                            PermissionName = "SYSTEM_ADMIN"
                        },
                        new
                        {
                            PermissionId = 105,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3534),
                            Description = "Database management operations",
                            PermissionName = "DATABASE_MANAGEMENT"
                        },
                        new
                        {
                            PermissionId = 106,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3537),
                            Description = "Backup and restore operations",
                            PermissionName = "BACKUP_RESTORE"
                        },
                        new
                        {
                            PermissionId = 107,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3539),
                            Description = "Access audit trail information",
                            PermissionName = "AUDIT_TRAIL"
                        },
                        new
                        {
                            PermissionId = 108,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(3542),
                            Description = "Security configuration management",
                            PermissionName = "SECURITY_MANAGEMENT"
                        });
                });

            modelBuilder.Entity("BitRaserApiProject.Models.PermissionRoute", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RouteId");

                    b.HasIndex("RouteId");

                    b.ToTable("PermissionRoutes");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.ReportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ReportTemplates");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(2666),
                            Description = "Full system access",
                            HierarchyLevel = 1,
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(2671),
                            Description = "Administrative access",
                            HierarchyLevel = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(2675),
                            Description = "Management access",
                            HierarchyLevel = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(2679),
                            Description = "Support access",
                            HierarchyLevel = 4,
                            RoleName = "Support"
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 30, 34, 896, DateTimeKind.Utc).AddTicks(2682),
                            Description = "Basic user access",
                            HierarchyLevel = 5,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("BitRaserApiProject.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 5
                        });
                });

            modelBuilder.Entity("BitRaserApiProject.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("RouteId");

                    b.HasIndex("RoutePath", "HttpMethod")
                        .IsUnique();

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.ScheduledReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HourOfDay")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastRunDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NextRunDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecipientEmails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReportTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ScheduledReports");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.Sessions", b =>
                {
                    b.Property<int>("session_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("device_info")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("login_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("logout_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("session_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("session_id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.SubuserRole", b =>
                {
                    b.Property<int>("SubuserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssignedByEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SubuserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("SubuserRoles");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystemSetting")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "SettingKey")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.Update", b =>
                {
                    b.Property<int>("version_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("auto_download_enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("changelog")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("checksum_md5")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("checksum_sha256")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by_email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("deprecation_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("download_link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("file_size_bytes")
                        .HasColumnType("bigint");

                    b.Property<string>("installation_notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("is_mandatory_update")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("minimum_os_version")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("release_date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("requires_restart")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("rollback_version")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("security_notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("supported_platforms")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("update_status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("update_type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("version_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("version_id");

                    b.ToTable("Updates");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssignedByEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.User_role_profile", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("manage_user_id")
                        .HasColumnType("int");

                    b.Property<string>("role_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("role_id");

                    b.ToTable("User_role_profile");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.audit_reports", b =>
                {
                    b.Property<int>("report_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("client_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("erasure_method")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("report_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("report_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("report_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("synced")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("report_id");

                    b.ToTable("AuditReports");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.logs", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("log_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("log_level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("log_message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("log_id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.machines", b =>
                {
                    b.Property<string>("fingerprint_hash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("bios_serial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cpu_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("demo_usage_count")
                        .HasColumnType("int");

                    b.Property<bool>("license_activated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("license_activation_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("license_days_valid")
                        .HasColumnType("int");

                    b.Property<string>("license_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("mac_address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("os_version")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("physical_drive_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("subuser_email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("vm_status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("fingerprint_hash");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.subuser", b =>
                {
                    b.Property<int>("subuser_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("AssignedMachines")
                        .HasColumnType("int");

                    b.Property<bool>("CanAssignLicenses")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanCreateSubusers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanManageMachines")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanViewReports")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LicenseIdsJson")
                        .HasColumnType("json");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MachineIdsJson")
                        .HasColumnType("json");

                    b.Property<int?>("MaxMachines")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PermissionsJson")
                        .HasColumnType("json");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("SystemAlerts")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("subuser_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("subuser_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("subuser_username")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("superuser_id")
                        .HasColumnType("int");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("subuser_id");

                    b.HasIndex("subuser_email")
                        .IsUnique();

                    b.ToTable("subuser");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("hash_password")
                        .HasColumnType("longtext");

                    b.Property<bool?>("is_private_cloud")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("license_allocation")
                        .HasColumnType("int");

                    b.Property<string>("license_details_json")
                        .HasColumnType("json");

                    b.Property<string>("payment_details_json")
                        .HasColumnType("json");

                    b.Property<string>("phone_number")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("private_api")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_group")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_role")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("user_id");

                    b.HasIndex("user_email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.PermissionRoute", b =>
                {
                    b.HasOne("BitRaserApiProject.Models.Permission", "Permission")
                        .WithMany("PermissionRoutes")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitRaserApiProject.Models.Route", "Route")
                        .WithMany("PermissionRoutes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.RolePermission", b =>
                {
                    b.HasOne("BitRaserApiProject.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitRaserApiProject.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.SubuserRole", b =>
                {
                    b.HasOne("BitRaserApiProject.Models.Role", "Role")
                        .WithMany("SubuserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BitRaserApiProject.Models.subuser", "Subuser")
                        .WithMany("SubuserRoles")
                        .HasForeignKey("SubuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Subuser");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.UserRole", b =>
                {
                    b.HasOne("BitRaserApiProject.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitRaserApiProject.Models.users", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.Permission", b =>
                {
                    b.Navigation("PermissionRoutes");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("SubuserRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.Route", b =>
                {
                    b.Navigation("PermissionRoutes");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.subuser", b =>
                {
                    b.Navigation("SubuserRoles");
                });

            modelBuilder.Entity("BitRaserApiProject.Models.users", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
