// <auto-generated />
using System;
using BitRaserApiProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitRaserApiProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250926082901_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BitRaserApiProject.Commands", b =>
                {
                    b.Property<int>("Command_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("command_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("command_status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("command_text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("issued_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Command_id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("BitRaserApiProject.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(1184),
                            Description = "Complete system access",
                            PermissionName = "FullAccess"
                        },
                        new
                        {
                            PermissionId = 2,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(1185),
                            Description = "Manage users and subusers",
                            PermissionName = "UserManagement"
                        },
                        new
                        {
                            PermissionId = 3,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(1187),
                            Description = "Access and manage reports",
                            PermissionName = "ReportAccess"
                        },
                        new
                        {
                            PermissionId = 4,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(1188),
                            Description = "Manage machines",
                            PermissionName = "MachineManagement"
                        },
                        new
                        {
                            PermissionId = 5,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(1190),
                            Description = "Read-only access",
                            PermissionName = "ViewOnly"
                        },
                        new
                        {
                            PermissionId = 6,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(1191),
                            Description = "Manage licenses",
                            PermissionName = "LicenseManagement"
                        },
                        new
                        {
                            PermissionId = 7,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(1193),
                            Description = "Access system logs",
                            PermissionName = "SystemLogs"
                        });
                });

            modelBuilder.Entity("BitRaserApiProject.PermissionRoute", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RouteId");

                    b.HasIndex("RouteId");

                    b.ToTable("PermissionRoutes");
                });

            modelBuilder.Entity("BitRaserApiProject.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(939),
                            Description = "Full system access",
                            HierarchyLevel = 1,
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(942),
                            Description = "Administrative access",
                            HierarchyLevel = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(944),
                            Description = "Management access",
                            HierarchyLevel = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(945),
                            Description = "Support access",
                            HierarchyLevel = 4,
                            RoleName = "Support"
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2025, 9, 26, 8, 29, 1, 424, DateTimeKind.Utc).AddTicks(947),
                            Description = "Basic user access",
                            HierarchyLevel = 5,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("BitRaserApiProject.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 5
                        });
                });

            modelBuilder.Entity("BitRaserApiProject.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("RouteId");

                    b.HasIndex("RoutePath", "HttpMethod")
                        .IsUnique();

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("BitRaserApiProject.Sessions", b =>
                {
                    b.Property<int>("session_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("device_info")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ip_address")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("login_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("logout_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("session_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("session_id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BitRaserApiProject.SubuserRole", b =>
                {
                    b.Property<int>("SubuserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssignedByEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SubuserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("SubuserRoles");
                });

            modelBuilder.Entity("BitRaserApiProject.Update", b =>
                {
                    b.Property<int>("version_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("changelog")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("download_link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("is_mandatory_update")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("release_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("version_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("version_id");

                    b.ToTable("Updates");
                });

            modelBuilder.Entity("BitRaserApiProject.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssignedByEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BitRaserApiProject.User_role_profile", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("manage_user_id")
                        .HasColumnType("int");

                    b.Property<string>("role_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("role_id");

                    b.ToTable("User_role_profile");
                });

            modelBuilder.Entity("BitRaserApiProject.audit_reports", b =>
                {
                    b.Property<int>("report_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("client_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("erasure_method")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("report_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("report_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("report_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("synced")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("report_id");

                    b.ToTable("AuditReports");
                });

            modelBuilder.Entity("BitRaserApiProject.logs", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("log_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("log_level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("log_message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("log_id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("BitRaserApiProject.machines", b =>
                {
                    b.Property<string>("fingerprint_hash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("bios_serial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cpu_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("demo_usage_count")
                        .HasColumnType("int");

                    b.Property<bool>("license_activated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("license_activation_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("license_days_valid")
                        .HasColumnType("int");

                    b.Property<string>("license_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("mac_address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("os_version")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("physical_drive_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("subuser_email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("vm_status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("fingerprint_hash");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("BitRaserApiProject.subuser", b =>
                {
                    b.Property<int>("subuser_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("subuser_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("subuser_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("superuser_id")
                        .HasColumnType("int");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("subuser_id");

                    b.ToTable("subuser");
                });

            modelBuilder.Entity("BitRaserApiProject.users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("hash_password")
                        .HasColumnType("longtext");

                    b.Property<bool>("is_private_cloud")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("license_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("payment_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("private_api")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("user_id");

                    b.HasIndex("user_email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BitRaserApiProject.PermissionRoute", b =>
                {
                    b.HasOne("BitRaserApiProject.Permission", "Permission")
                        .WithMany("PermissionRoutes")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitRaserApiProject.Route", "Route")
                        .WithMany("PermissionRoutes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("BitRaserApiProject.RolePermission", b =>
                {
                    b.HasOne("BitRaserApiProject.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitRaserApiProject.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BitRaserApiProject.SubuserRole", b =>
                {
                    b.HasOne("BitRaserApiProject.Role", "Role")
                        .WithMany("SubuserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitRaserApiProject.subuser", "Subuser")
                        .WithMany("SubuserRoles")
                        .HasForeignKey("SubuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Subuser");
                });

            modelBuilder.Entity("BitRaserApiProject.UserRole", b =>
                {
                    b.HasOne("BitRaserApiProject.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitRaserApiProject.users", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BitRaserApiProject.Permission", b =>
                {
                    b.Navigation("PermissionRoutes");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BitRaserApiProject.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("SubuserRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BitRaserApiProject.Route", b =>
                {
                    b.Navigation("PermissionRoutes");
                });

            modelBuilder.Entity("BitRaserApiProject.subuser", b =>
                {
                    b.Navigation("SubuserRoles");
                });

            modelBuilder.Entity("BitRaserApiProject.users", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
