using BitRaserApiProject.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;


public class PdfService
{
    public byte[] GenerateReport(ReportRequest request)
    {
        var pdf = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.Size(PageSizes.A4);

                page.Header()
                    .Text("D-SecureErase Report")
                    .FontSize(22).SemiBold().FontColor(Colors.Blue.Medium);

                page.Content().PaddingVertical(20).Column(col =>
                {
                    // Process Status Section
                    col.Item().Text("Process Status").FontSize(16).SemiBold();
                    col.Item().Text($"Process Status: {request.ProcessStatus}");
                    col.Item().Text($"Process Mode: {request.ProcessMode}");
                    col.Item().PaddingVertical(10).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                    col.Item().PaddingVertical(10);

                    // Report Info Section
                    col.Item().Text("Report Info").FontSize(16).SemiBold();
                    col.Item().Text($"Report ID: {request.ReportId}");
                    col.Item().Text($"Report Date: {request.ReportDate:yyyy-MM-dd HH:mm:ss}");
                    col.Item().Text($"Software: {request.Software}");
                    col.Item().Text($"Digital Identifier: {request.DigitalIdentifier}");
                    col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                    col.Item().PaddingVertical(10);

                    // Annexure Logs
                    col.Item().Text("Annexure: Erasure Log").FontSize(16).SemiBold();

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.ConstantColumn(100);
                            columns.ConstantColumn(80);
                            columns.ConstantColumn(120);
                            columns.ConstantColumn(120);
                            columns.RelativeColumn();
                        });

                        // Header
                        table.Header(header =>
                        {
                            header.Cell().Text("Volume").SemiBold();
                            header.Cell().Text("Capacity").SemiBold();
                            header.Cell().Text("Total Sectors").SemiBold();
                            header.Cell().Text("Sectors Erased").SemiBold();
                            header.Cell().Text("Status").SemiBold();
                        });

                        // Rows
                        foreach (var log in request.Logs)
                        {
                            table.Cell().Text(log.Volume);
                            table.Cell().Text(log.Capacity);
                            table.Cell().Text(log.TotalSectors.ToString());
                            table.Cell().Text(log.ErasedSectors.ToString());
                            table.Cell().Text(log.Status);
                        }
                    });
                });

                page.Footer()
                    .AlignCenter()
                    .Text(txt =>
                    {
                        txt.Span("Generated by BitRaser API ").FontSize(10);
                        txt.Span($" | {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}").FontSize(10);
                    });
            });
        });

        return pdf.GeneratePdf();
    }

}
