// <auto-generated />
using System;
using BitRaserApiProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitRaserApiProject.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BitRaserApiProject.Update", b =>
                {
                    b.Property<int>("version_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("changelog")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("download_link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("is_mandatory_update")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("release_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("version_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("version_id");

                    b.ToTable("Updates");
                });

            modelBuilder.Entity("BitRaserApiProject.audit_reports", b =>
                {
                    b.Property<int>("report_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("client_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("erasure_method")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("report_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("report_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("report_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("synced")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("report_id");

                    b.ToTable("AuditReports");
                });

            modelBuilder.Entity("BitRaserApiProject.machines", b =>
                {
                    b.Property<string>("fingerprint_hash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("bios_serial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cpu_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("license_activation_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("license_days_valid")
                        .HasColumnType("int");

                    b.Property<string>("license_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("mac_address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("os_version")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("physical_drive_id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("fingerprint_hash");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("BitRaserApiProject.users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("license_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("payment_details_json")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("user_id");

                    b.HasIndex("user_email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
